    name: Welcome new contributors
    on:
      pull_request:
        types: [opened]
      issues:
        types: [opened]
    jobs:
      welcome:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/first-interaction@v1
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              issue-message: "Welcome to the repository!  This is an automated message. Please feel free to ask any questions."
              pr-message: "Welcome to the repository!  This is an automated message. Please feel free to ask any questions."
